apiVersion: influxdata.com/v2alpha1
kind: Task
metadata:
    name: fetch-bitcoin-data
spec:
    every: 5m
    name: Fetch Bitcoin Data
    query: |-
        import "experimental/csv"

        csv.from(url: "https://raw.githubusercontent.com/russorat/influxdb-data-examples/master/com/coindesk/bitcoin/currentprice-annotated.csv")
        |> to(bucket: "sample_data")
    status: active
