apiVersion: influxdata.com/v2alpha1
kind: Task
metadata:
    name: fetch-noaa-ndbc-task
spec:
    every: 5m
    name: Fetch NOAA NDBC Data
    query: |-
        import "experimental/csv"

        csv.from(url: "https://raw.githubusercontent.com/influxdata/influxdb2-sample-data/master/noaa-ndbc-data/latest-observations-annotated.csv")
        |> to(bucket: "sample_data")
    status: active
