apiVersion: influxdata.com/v2alpha1
kind: Task
metadata:
    name: fetch-sample-data
spec:
    every: 5m
    name: Fetch Sample Data
    query: |-
        import "experimental/csv"

        csv.from(url: "https://raw.githubusercontent.com/russorat/influxdb-data-examples/master/com/coindesk/bitcoin/currentprice-annotated.csv")
        |> to(bucket: "sample_data")

        csv.from(url: "https://raw.githubusercontent.com/influxdata/influxdb2-sample-data/master/usgs-earthquake-data/all_week-annotated.csv")
        |> to(bucket: "sample_data")

        csv.from(url: "https://raw.githubusercontent.com/influxdata/influxdb2-sample-data/master/noaa-ndbc-data/latest-observations-annotated.csv")
        |> to(bucket: "sample_data")

        csv.from(url: "https://raw.githubusercontent.com/influxdata/influxdb2-sample-data/master/air-sensor-data/air-sensor-data-annotated.csv")
        |> to(bucket: "sample_data")
    status: active
---
apiVersion: influxdata.com/v2alpha1
kind: Bucket
metadata:
    name: sample-data-bucket
spec:
    name: sample_data
    retentionRules:
      - everySeconds: 604800
        type: expire