apiVersion: influxdata.com/v2alpha1
kind: Bucket
metadata:
    name: telegraf-1d-bucket
spec:
    name: telegraf_1d
    retentionRules:
    - everySeconds: 2.592e+6
      type: expire
---
apiVersion: influxdata.com/v2alpha1
kind: Bucket
metadata:
    name: telegraf-bucket
spec:
    name: telegraf
    retentionRules:
    - everySeconds: 2.592e+6
      type: expire
---
apiVersion: influxdata.com/v2alpha1
kind: Bucket
metadata:
    name: telegraf-1h-bucket
spec:
    name: telegraf_1h
    retentionRules:
    - everySeconds: 2.592e+6
      type: expire
---
apiVersion: influxdata.com/v2alpha1
kind: Bucket
metadata:
    name: telegraf-1m-bucket
spec:
    name: telegraf_1m
    retentionRules:
    - everySeconds: 2.592e+6
      type: expire
---
apiVersion: influxdata.com/v2alpha1
kind: Bucket
metadata:
    name: telegraf-10m-bucket
spec:
    name: telegraf_10m
    retentionRules:
    - everySeconds: 2.592e+6
      type: expire
