apiVersion: influxdata.com/v2alpha1
kind: Label
metadata:
    name: raspberry-pi-label
spec:
    color: '#c6f98e'
    name: raspberry pi
---
apiVersion: influxdata.com/v2alpha1
kind: Label
metadata:
    name: enviro-plus-label
spec:
    color: '#FFF6B8'
    name: enviro+
---
apiVersion: influxdata.com/v2alpha1
kind: Label
metadata:
    name: air-quality-label
spec:
    color: '#326BBA'
    name: air quality
---
apiVersion: influxdata.com/v2alpha1
kind: Dashboard
metadata:
    name: enviro-plus-dashboard
spec:
    associations:
      - kind: Label
        name: raspberry-pi-label
      - kind: Label
        name: enviro-plus-label
      - kind: Label
        name: air-quality-label
    charts:
      - axes:
          - base: "10"
            name: x
            scale: linear
          - base: "10"
            name: y
            scale: linear
        colors:
          - hex: '#31C0F6'
            name: Nineteen Eighty Four
            type: scale
          - hex: '#A500A5'
            name: Nineteen Eighty Four
            type: scale
          - hex: '#FF7E27'
            name: Nineteen Eighty Four
            type: scale
        geom: line
        height: 4
        kind: Xy
        name: Temperature
        position: overlaid
        queries:
          - query: |-
                from(bucket: "enviroplus")
                  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
                  |> filter(fn: (r) => r["_measurement"] == "enviroplus")
                  |> filter(fn: (r) => r["_field"] == "temperature")
        shade: true
        width: 4
        xCol: _time
        yCol: _value
      - axes:
          - base: "10"
            name: x
            scale: linear
          - base: "10"
            name: y
            scale: linear
        colors:
          - hex: '#74D495'
            name: Atlantis
            type: scale
          - hex: '#3F3FBA'
            name: Atlantis
            type: scale
          - hex: '#FF4D9E'
            name: Atlantis
            type: scale
        geom: line
        height: 4
        kind: Xy
        name: Humidity
        position: overlaid
        queries:
          - query: |-
                from(bucket: "enviroplus")
                  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
                  |> filter(fn: (r) => r["_measurement"] == "enviroplus")
                  |> filter(fn: (r) => r["_field"] == "humidity")
        shade: true
        width: 4
        xCol: _time
        yCol: _value
        yPos: 4
      - axes:
          - base: "10"
            name: x
            scale: linear
          - base: "10"
            name: y
            scale: linear
        colors:
          - hex: '#74D495'
            name: Atlantis
            type: scale
          - hex: '#3F3FBA'
            name: Atlantis
            type: scale
          - hex: '#FF4D9E'
            name: Atlantis
            type: scale
        geom: line
        height: 4
        kind: Xy
        name: Proximity
        position: overlaid
        queries:
          - query: |-
                from(bucket: "enviroplus")
                  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
                  |> filter(fn: (r) => r["_measurement"] == "enviroplus")
                  |> filter(fn: (r) => r["_field"] == "proximity")
        shade: true
        width: 4
        xCol: _time
        yCol: _value
        yPos: 8
      - axes:
          - base: "10"
            name: x
            scale: linear
          - base: "10"
            name: y
            scale: linear
        colors:
          - hex: '#74D495'
            name: Atlantis
            type: scale
          - hex: '#3F3FBA'
            name: Atlantis
            type: scale
          - hex: '#FF4D9E'
            name: Atlantis
            type: scale
        geom: line
        height: 4
        kind: Xy
        name: PM
        position: overlaid
        queries:
          - query: |-
                from(bucket: "enviroplus")
                  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
                  |> filter(fn: (r) => r["_measurement"] == "enviroplus")
                  |> filter(fn: (r) => r["_field"] == "pm1" or r["_field"] == "pm10" or r["_field"] == "pm25")
        shade: true
        width: 4
        xCol: _time
        xPos: 4
        yCol: _value
      - axes:
          - base: "10"
            name: x
            scale: linear
          - base: "10"
            name: y
            scale: linear
        colors:
          - hex: '#74D495'
            name: Atlantis
            type: scale
          - hex: '#3F3FBA'
            name: Atlantis
            type: scale
          - hex: '#FF4D9E'
            name: Atlantis
            type: scale
        geom: line
        height: 4
        kind: Xy
        name: Pressure
        position: overlaid
        queries:
          - query: |-
                from(bucket: "enviroplus")
                  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
                  |> filter(fn: (r) => r["_measurement"] == "enviroplus")
                  |> filter(fn: (r) => r["_field"] == "pressure")
        shade: true
        width: 4
        xCol: _time
        xPos: 4
        yCol: _value
        yPos: 4
      - axes:
          - base: "10"
            name: x
            scale: linear
          - base: "10"
            name: y
            scale: linear
        colors:
          - hex: '#74D495'
            name: Atlantis
            type: scale
          - hex: '#3F3FBA'
            name: Atlantis
            type: scale
          - hex: '#FF4D9E'
            name: Atlantis
            type: scale
        geom: line
        height: 4
        kind: Xy
        name: Gas
        position: overlaid
        queries:
          - query: |-
                from(bucket: "enviroplus")
                  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
                  |> filter(fn: (r) => r["_measurement"] == "enviroplus")
                  |> filter(fn: (r) => r["_field"] == "oxidising" or r["_field"] == "reducing" or r["_field"] == "nh3")
        shade: true
        width: 4
        xCol: _time
        xPos: 8
        yCol: _value
      - axes:
          - base: "10"
            name: x
            scale: linear
          - base: "10"
            name: y
            scale: linear
        colors:
          - hex: '#74D495'
            name: Atlantis
            type: scale
          - hex: '#3F3FBA'
            name: Atlantis
            type: scale
          - hex: '#FF4D9E'
            name: Atlantis
            type: scale
        geom: line
        height: 4
        kind: Xy
        name: Lux
        position: overlaid
        queries:
          - query: |-
                from(bucket: "enviroplus")
                  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
                  |> filter(fn: (r) => r["_measurement"] == "enviroplus")
                  |> filter(fn: (r) => r["_field"] == "lux")
        shade: true
        width: 4
        xCol: _time
        xPos: 8
        yCol: _value
        yPos: 4
    description: A template for viewing Air Quality data from a Pimoroni Enviro+
    name: Enviro Plus
