apiVersion: influxdata.com/v2alpha1
kind: Telegraf
metadata:
    name: telegraf-smart-input-config
spec:
    description: A Telegraf config with the S.M.A.R.T. plugin enabled
    name: Telegraf S.M.A.R.T. Plugin Configuration
    config: |
        # Telegraf Configuration
        #
        # Telegraf is entirely plugin driven. All metrics are gathered from the
        # declared inputs, and sent to the declared outputs.
        #
        # Plugins must be declared in here to be active.
        # To deactivate a plugin, comment out the name and any variables.
        #
        # Use 'telegraf -config telegraf.conf -test' to see what metrics a config
        # file would generate.
        #
        # Environment variables can be used anywhere in this config file, simply surround
        # them with ${}. For strings the variable must be within quotes (ie, "${STR_VAR}"),
        # for numbers and booleans they should be plain (ie, ${INT_VAR}, ${BOOL_VAR})
        
        
        # Global tags can be specified here in key="value" format.
        [global_tags]
        # dc = "us-east-1" # will tag all metrics with dc=us-east-1
        # rack = "1a"
        ## Environment variables can be used as tags, and throughout the config file
        # user = "$USER"
        
        
        # Configuration for telegraf agent
        [agent]
        ## Default data collection interval for all inputs
        interval = "10s"
        ## Rounds collection interval to 'interval'
        ## ie, if interval="10s" then always collect on :00, :10, :20, etc.
        round_interval = true
        
        ## Telegraf will send metrics to outputs in batches of at most
        ## metric_batch_size metrics.
        ## This controls the size of writes that Telegraf sends to output plugins.
        metric_batch_size = 1000
        
        ## Maximum number of unwritten metrics per output.  Increasing this value
        ## allows for longer periods of output downtime without dropping metrics at the
        ## cost of higher maximum memory usage.
        metric_buffer_limit = 10000
        
        ## Collection jitter is used to jitter the collection by a random amount.
        ## Each plugin will sleep for a random time within jitter before collecting.
        ## This can be used to avoid many plugins querying things like sysfs at the
        ## same time, which can have a measurable effect on the system.
        collection_jitter = "0s"
        
        ## Default flushing interval for all outputs. Maximum flush_interval will be
        ## flush_interval + flush_jitter
        flush_interval = "10s"
        ## Jitter the flush interval by a random amount. This is primarily to avoid
        ## large write spikes for users running a large number of telegraf instances.
        ## ie, a jitter of 5s and interval 10s means flushes will happen every 10-15s
        flush_jitter = "0s"
        
        ## By default or when set to "0s", precision will be set to the same
        ## timestamp order as the collection interval, with the maximum being 1s.
        ##   ie, when interval = "10s", precision will be "1s"
        ##       when interval = "250ms", precision will be "1ms"
        ## Precision will NOT be used for service inputs. It is up to each individual
        ## service input to set the timestamp at the appropriate precision.
        ## Valid time units are "ns", "us" (or "µs"), "ms", "s".
        precision = ""
        
        ## Log at debug level.
        # debug = false
        ## Log only error level messages.
        # quiet = false
        
        ## Log target controls the destination for logs and can be one of "file",
        ## "stderr" or, on Windows, "eventlog".  When set to "file", the output file
        ## is determined by the "logfile" setting.
        # logtarget = "file"
        
        ## Name of the file to be logged to when using the "file" logtarget.  If set to
        ## the empty string then logs are written to stderr.
        # logfile = ""
        
        ## The logfile will be rotated after the time interval specified.  When set
        ## to 0 no time based rotation is performed.  Logs are rotated only when
        ## written to, if there is no log activity rotation may be delayed.
        # logfile_rotation_interval = "0d"
        
        ## The logfile will be rotated when it becomes larger than the specified
        ## size.  When set to 0 no size based rotation is performed.
        # logfile_rotation_max_size = "0MB"
        
        ## Maximum number of rotated archives to keep, any older logs are deleted.
        ## If set to -1, no archives are removed.
        # logfile_rotation_max_archives = 5
        
        ## Override default hostname, if empty use os.Hostname()
        hostname = ""
        ## If set to true, do no set the "host" tag in the telegraf agent.
        omit_hostname = false
        
        
        ###############################################################################
        #                            OUTPUT PLUGINS                                   #
        ###############################################################################
        
        # # Configuration for sending metrics to InfluxDB
        [[outputs.influxdb_v2]]
        ## The URLs of the InfluxDB cluster nodes.
        ##
        ## Multiple URLs can be specified for a single cluster, only ONE of the
        ## urls will be written to each interval.
        urls = ["http://localhost:9999"]
        
        ## Token for authentication.
        token = "$INFLUX_TOKEN"
        
        ## Organization is the name of the organization you wish to write to.
        organization = "$INFLUX_ORG"
        
        ## Bucket to the name fo the bucket to write into; must exist.
        bucket = "telegraf"
        
        #
        #   ## The value of this tag will be used to determine the bucket.  If this
        #   ## tag is not set the 'bucket' option is used as the default.
        #   # bucket_tag = ""
        #
        #   ## If true, the bucket tag will not be added to the metric.
        #   # exclude_bucket_tag = false
        #
        #   ## Timeout for HTTP messages.
        #   # timeout = "5s"
        #
        #   ## Additional HTTP headers
        #   # http_headers = {"X-Special-Header" = "Special-Value"}
        #
        #   ## HTTP Proxy override, if unset values the standard proxy environment
        #   ## variables are consulted to determine which proxy, if any, should be used.
        #   # http_proxy = "http://corporate.proxy:3128"
        #
        #   ## HTTP User-Agent
        #   # user_agent = "telegraf"
        #
        #   ## Content-Encoding for write request body, can be set to "gzip" to
        #   ## compress body or "identity" to apply no encoding.
        #   # content_encoding = "gzip"
        #
        #   ## Enable or disable uint support for writing uints influxdb 2.0.
        #   # influx_uint_support = false
        #
        #   ## Optional TLS Config for use on HTTP connections.
        #   # tls_ca = "/etc/telegraf/ca.pem"
        #   # tls_cert = "/etc/telegraf/cert.pem"
        #   # tls_key = "/etc/telegraf/key.pem"
        #   ## Use TLS but skip chain & host verification
        #   # insecure_skip_verify = false
        
        ###############################################################################
        #                            INPUT PLUGINS                                    #
        ###############################################################################
        
        
        # Read metrics from storage devices supporting S.M.A.R.T.
        [[inputs.smart]]
        ## Optionally specify the path to the smartctl executable
        # path = "/usr/bin/smartctl"

        ## On most platforms smartctl requires root access.
        ## Setting 'use_sudo' to true will make use of sudo to run smartctl.
        ## Sudo must be configured to to allow the telegraf user to run smartctl
        ## without a password.
        # use_sudo = false

        ## Skip checking disks in this power mode. Defaults to
        ## "standby" to not wake up disks that have stoped rotating.
        ## See --nocheck in the man pages for smartctl.
        ## smartctl version 5.41 and 5.42 have faulty detection of
        ## power mode and might require changing this value to
        ## "never" depending on your disks.
        # nocheck = "standby"

        ## Gather all returned S.M.A.R.T. attribute metrics and the detailed
        ## information from each drive into the `smart_attribute` measurement.
        # attributes = false

        ## Optionally specify devices to exclude from reporting.
        # excludes = [ "/dev/pass6" ]

        ## Optionally specify devices and device type, if unset
        ## a scan (smartctl --scan) for S.M.A.R.T. devices will
        ## done and all found will be included except for the
        ## excluded in excludes.
        # devices = [ "/dev/ada0 -d atacam" ]

        ## Timeout for the smartctl command to complete.
        # timeout = "30s"